version: "3"
###########################################
networks:
  hyc-demo:
    name: hyc-demo
    driver: bridge
###########################################
services:
#-----------------------------------------#
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "5001:5000"
    networks:
      - hyc-demo
#-----------------------------------------#
  gitea:
    image: gitea/gitea:1.12.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - hyc-demo
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
###########################################
volumes:
  k3s-server: {}
