version: "3"
networks:
  hyc:
    name: hyc
    driver: bridge
services:
  gitea:
    image: gitea/gitea:1.12.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - hyc
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
