bases:
  - ../base

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: flux
      namespace: flux
    path: flux-args.patch.yaml

generatorOptions:
  disableNameSuffixHash: true

