apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      volumes:
        - name: ssh-config
          configMap:
            name: flux-ssh-config
      containers:
        - name: flux
          volumeMounts:
            - name: ssh-config
              mountPath: /root/.ssh