bases:
  - ../base

patches:
  - flux-ssh-config-patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: flux
  path: flux-args.patch.yaml

resources:
  - coredns.patch.yaml
  - flux-ssh-config.yaml